Improve specs to be more useful -> input: region, month, year, dayofweek, daytime(hourly), brand output: price

In [1]:
import sklearn
import numpy as np
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres@localhost:5432/history')

In [21]:
#read input data from sql database
data = pd.read_sql_query("""select
            extract(year from gsih.date) as "year", 
            extract(month from gsih.date) as "moth", 
            extract(dow from gsih.date) as "dow", 
            extract(hour from gsih.date) as "hour", 
            left(gs.post_code, 3) as "region", 
            gs.brand,
            avg(NULLIF(NULLIF(NULLIF(diesel, 888), 0), -1)) as "diesel"
            FROM gas_station gs JOIN gas_station_information_history gsih ON gs.id = gsih.stid 
            group by 1, 2, 3, 4, 5, 6;""",
            con=engine)

#encode hour into sinus to be countinuous
data['sin_hour'] = np.sin(2*np.pi*data.hour/24)
#drop all 'Nicht mehr Aktiv'
data = data[data.brand != 'Nicht mehr aktiv']
data = data[data.brand != 'nicht mehr aktiv']

OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
 [SQL: 'select\n            extract(year from gsih.date) as "year", \n            extract(month from gsih.date) as "moth", \n            extract(dow from gsih.date) as "dow", \n            extract(hour from gsih.date) as "hour", \n            left(gs.post_code, 3) as "region", \n            gs.brand,\n            avg(NULLIF(NULLIF(NULLIF(diesel, 888), 0), -1)) as "diesel"\n            FROM gas_station gs JOIN gas_station_information_history gsih ON gs.id = gsih.stid \n            group by 1, 2, 3, 4, 5, 6;'] (Background on this error at: http://sqlalche.me/e/e3q8)

In [80]:
data

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>year</th>
      <th>moth</th>
      <th>dow</th>
      <th>hour</th>
      <th>region</th>
      <th>brand</th>
      <th>diesel</th>
      <th>sin_hour</th>
      <th>brand_cat</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>012</td>
      <td>STAR</td>
      <td>1079.000000</td>
      <td>0.000000</td>
      <td>7</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>027</td>
      <td>Tankstelle</td>
      <td>1119.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>041</td>
      <td>Q1</td>
      <td>1109.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>065</td>
      <td>Raiffeisen Mansfeld</td>
      <td>1159.000000</td>
      <td>0.000000</td>
      <td>9</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>075</td>
      <td>bft - Walther</td>
      <td>1134.000000</td>
      <td>0.000000</td>
      <td>12</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>075</td>
      <td>STAR</td>
      <td>1089.000000</td>
      <td>0.000000</td>
      <td>7</td>
    </tr>
    <tr>
      <th>6</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>080</td>
      <td>C&amp;S</td>
      <td>1149.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>091</td>
      <td>bft - Walther</td>
      <td>1164.000000</td>
      <td>0.000000</td>
      <td>12</td>
    </tr>
    <tr>
      <th>8</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>158</td>
      <td>Q1</td>
      <td>1139.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>9</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>172</td>
      <td>HEM</td>
      <td>1094.000000</td>
      <td>0.000000</td>
      <td>10</td>
    </tr>
    <tr>
      <th>10</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>183</td>
      <td>ADAP Tankstelle</td>
      <td>1089.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>184</td>
      <td>ADAP Tankstelle</td>
      <td>1099.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>12</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>190</td>
      <td>OIL!</td>
      <td>1101.500000</td>
      <td>0.000000</td>
      <td>13</td>
    </tr>
    <tr>
      <th>13</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>190</td>
      <td>None</td>
      <td>1069.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>205</td>
      <td>ESSO</td>
      <td>1109.000000</td>
      <td>0.000000</td>
      <td>3</td>
    </tr>
    <tr>
      <th>15</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>205</td>
      <td>freie Tankstelle</td>
      <td>1049.000000</td>
      <td>0.000000</td>
      <td>12</td>
    </tr>
    <tr>
      <th>16</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>210</td>
      <td>STAR</td>
      <td>1079.000000</td>
      <td>0.000000</td>
      <td>7</td>
    </tr>
    <tr>
      <th>17</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>213</td>
      <td>BeckmannLindemann GmbH</td>
      <td>1079.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>18</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>216</td>
      <td>NORDOEL</td>
      <td>1049.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>217</td>
      <td>Raiffeisen - LBAG Schmalenbrücke eG</td>
      <td>1084.000000</td>
      <td>0.000000</td>
      <td>9</td>
    </tr>
    <tr>
      <th>20</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>236</td>
      <td>Weidemann-Tank</td>
      <td>1089.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>21</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>238</td>
      <td>LOTHEROL</td>
      <td>1099.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>22</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>243</td>
      <td>team</td>
      <td>1105.666667</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>23</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>245</td>
      <td>Schillhorn Mineral"le GmbH Remmels</td>
      <td>1059.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>24</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>245</td>
      <td>SKY</td>
      <td>1089.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>25</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>247</td>
      <td>team</td>
      <td>1149.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>26</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>255</td>
      <td>Schillhorn Mineralöle GmbH Hanerau</td>
      <td>1059.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>27</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>257</td>
      <td>Schillhorn Mineralöle GmbH Gudendorf</td>
      <td>1059.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>28</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>257</td>
      <td>Schillhorn Mineralöle GmbH Hemme</td>
      <td>1059.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>29</th>
      <td>2016.0</td>
      <td>5.0</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>257</td>
      <td>Schillhorn Mineralöle GmbH Süderhastedt</td>
      <td>1059.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>19859046</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>960</td>
      <td>E-Center</td>
      <td>1299.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859047</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>961</td>
      <td>ESSO</td>
      <td>1339.000000</td>
      <td>-0.258819</td>
      <td>3</td>
    </tr>
    <tr>
      <th>19859048</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>961</td>
      <td>Freie Tankstelle</td>
      <td>1309.000000</td>
      <td>-0.258819</td>
      <td>12</td>
    </tr>
    <tr>
      <th>19859049</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>964</td>
      <td>E-Center</td>
      <td>1319.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859050</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>964</td>
      <td>ELO</td>
      <td>1279.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859051</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>964</td>
      <td>ESSO</td>
      <td>1339.000000</td>
      <td>-0.258819</td>
      <td>3</td>
    </tr>
    <tr>
      <th>19859052</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>970</td>
      <td>ESSO</td>
      <td>1289.000000</td>
      <td>-0.258819</td>
      <td>3</td>
    </tr>
    <tr>
      <th>19859053</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>970</td>
      <td>Freie Tankstelle</td>
      <td>1319.000000</td>
      <td>-0.258819</td>
      <td>12</td>
    </tr>
    <tr>
      <th>19859054</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>970</td>
      <td>HERM</td>
      <td>1309.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859055</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>971</td>
      <td>E Center</td>
      <td>1339.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859056</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>972</td>
      <td>ESSO</td>
      <td>1299.000000</td>
      <td>-0.258819</td>
      <td>3</td>
    </tr>
    <tr>
      <th>19859057</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>972</td>
      <td>Tankstelle Fischer</td>
      <td>1319.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859058</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>973</td>
      <td>E Center</td>
      <td>1339.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859059</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>973</td>
      <td>ESSO</td>
      <td>1339.000000</td>
      <td>-0.258819</td>
      <td>3</td>
    </tr>
    <tr>
      <th>19859060</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>974</td>
      <td>Leu Energie</td>
      <td>1299.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859061</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>974</td>
      <td>None</td>
      <td>1329.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859062</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>978</td>
      <td>ESSO</td>
      <td>1334.000000</td>
      <td>-0.258819</td>
      <td>3</td>
    </tr>
    <tr>
      <th>19859063</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>979</td>
      <td>E Center</td>
      <td>1319.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859064</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>979</td>
      <td>ZG Raiffeisen Energie</td>
      <td>1319.000000</td>
      <td>-0.258819</td>
      <td>9</td>
    </tr>
    <tr>
      <th>19859065</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>985</td>
      <td>AVIA</td>
      <td>1299.000000</td>
      <td>-0.258819</td>
      <td>5</td>
    </tr>
    <tr>
      <th>19859066</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>985</td>
      <td>ESSO</td>
      <td>1309.000000</td>
      <td>-0.258819</td>
      <td>3</td>
    </tr>
    <tr>
      <th>19859067</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>990</td>
      <td>ESSO</td>
      <td>1289.000000</td>
      <td>-0.258819</td>
      <td>3</td>
    </tr>
    <tr>
      <th>19859068</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>993</td>
      <td>ESSO</td>
      <td>1339.000000</td>
      <td>-0.258819</td>
      <td>3</td>
    </tr>
    <tr>
      <th>19859069</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>995</td>
      <td>Marktkauf</td>
      <td>1299.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859070</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>997</td>
      <td>Honsel</td>
      <td>1279.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859071</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>997</td>
      <td>Marktkauf</td>
      <td>1309.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859072</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>998</td>
      <td>bft</td>
      <td>1299.000000</td>
      <td>-0.258819</td>
      <td>12</td>
    </tr>
    <tr>
      <th>19859073</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>998</td>
      <td>Marktkauf</td>
      <td>1319.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
    <tr>
      <th>19859074</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>999</td>
      <td>bft</td>
      <td>1299.000000</td>
      <td>-0.258819</td>
      <td>12</td>
    </tr>
    <tr>
      <th>19859075</th>
      <td>2018.0</td>
      <td>8.0</td>
      <td>6.0</td>
      <td>23.0</td>
      <td>999</td>
      <td>RWZ-Kassel</td>
      <td>1299.000000</td>
      <td>-0.258819</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
<p>19859076 rows × 9 columns</p>
</div>

In [2]:
#either save or restore data
#pd.to_csv(r'backup.csv')
data = pd.read_csv(r'backup.csv')
#target does not need scaling in regression tasks
target = data.replace([np.inf, -np.inf], np.nan).dropna(axis=0)['diesel']

C:\Users\reti\AppData\Local\Programs\Python\Python35\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import FeatureUnion
import numpy as np

#num_attributes = ["year", "moth", "hour", "diesel", "region"]
num_attributes = ["year", "moth", "hour", "region"]
cat_attributes = ["dow"]

class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, *_):
        return self
    def transform(self, X, *_):
        return X[self.attribute_names].values
    def fit_transform(self, X, y=None, **fit_params):
        return self.fit(X).transform(X)

class RemoveInfNaN(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass
    def fit(self, *_):
        return self
    def transform(self, X, *_):
        return X.replace([np.inf, -np.inf], np.nan).dropna(axis=0)

class CategorizeBrand(BaseEstimator, TransformerMixin):
    def __init__(self, brand):
        self.brand = brand
    def fit(self, *_):
        return self
    def transform(self, X, *_):
        #putting brands into categories (here only brands with over 90 appearences are considered)
        brand_list = ['ARAL', 'Shell', 'ESSO', 'TOTAL', 'AVIA', 'JET', 'STAR', 'Agip', 'Raiffeisen', 'HEM', 'OMV', 'bft', 'OIL!', 
                      'Westfalen', 'CLASSIC', 'ED', 'BayWa', 'Supermarkt-Tankstelle am real,- Markt']
        X[self.brand] = X[self.brand].replace(['BFT', 'Freie Tankstelle', 'freie Tankstelle', 'bft'], ['bft', 'bft', 'bft', 'bft'], regex=True)
        X[self.brand] = X[self.brand].replace(['', 'None', None], [0,0,0])
        X[self.brand] = X[self.brand].replace(brand_list, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18], regex=True)
        X.loc[X[self.brand].apply(lambda x: type(x)==str), self.brand] = 0
        return X[self.brand].values.reshape(-1, 1)
    def fit_transform(self, X, y=None, **fit_params):
        return self.fit(X).transform(X)
        
num_pipeline = Pipeline([
    ('nanremover', RemoveInfNaN()),
    ('selector', DataFrameSelector(num_attributes)),
    ('std_scaler', StandardScaler()),
    ])

brand_pipeline = Pipeline([
    ('nanremover', RemoveInfNaN()),
    ('catbrand', CategorizeBrand("brand")),
    ('encoder', OneHotEncoder(handle_unknown='ignore')),
    ])

cat_pipeline = Pipeline([
    ('nanremover', RemoveInfNaN()),
    ('selector', DataFrameSelector(cat_attributes)),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
    ])

full_pipeline = FeatureUnion(transformer_list=[
    ("num_pipeline", num_pipeline),
    ("brand_pipeline", brand_pipeline),
    ("cat_pipeline", cat_pipeline),
    ])

train_set = full_pipeline.fit_transform(data)

C:\Users\reti\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [4]:
#either save or restore processed training set
#np.save('train_set.npy', train_set)
train_set = np.load('train_set.npy')
del data
data.info()

NameError: name 'data' is not defined

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

lin_reg = LinearRegression()
scores = cross_val_score(lin_reg, train_set, target, scoring="neg_mean_squared_error", cv=10)
lr_scores = np.sqrt(-scores)
print(lr_scores.mean(), lr_scores.std())

54.5279206508 10.0939671757

In [20]:
del scores
del lr_scores

In [ ]:
scores

In [7]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
tree_reg = DecisionTreeRegressor()
scores = cross_val_score(tree_reg, train_set.tolist(), target, scoring="neg_mean_squared_error", cv=10)
lr_scores = np.sqrt(-scores)
print(lr_scores.mean(), lr_scores.std())